### ISSUE TITLE
baseline.py: saving output probability (.npy file)

### ISSUE THREAD

**Issue by sudipansaha** [zxj32/uncertainty-GNN#1]
It seems like in baseline.py, when if FLAGS.OOD_detection == 0 output probability (.npy file) is not not saved and when FLAGS.OOD_detection == 1 output probability (.npy file) is saved, but without the _ood extension (i.e., to incorrect directory).

**Comment by zxj32** [comment]
Thanks for pointing out this error, I just fixed it,
